"""dono_id em produtos

Revision ID: 85a751fca4a2
Revises: 0ab8e5b11925
Create Date: 2026-09-16 23:58:03.586558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a751fca4a2'
down_revision: Union[str, Sequence[str], None] = '0ab8e5b11925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dono_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_produtos_dono', 'usuarios', ['dono_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_produtos_dono', type_='foreignkey')
        batch_op.drop_column('dono_id')

    # ### end Alembic commands ###
